### ISSUE TITLE
Column "authorship" does not exist.

### ISSUE THREAD

**Issue by tiirex9** [hackmdio/docker-hackmd#10]
Nach dem Start mit `docker-compose up` bekomme ich beim erstellen einer neuen Notiz einen HTTP 500 und im Log steht folgender Fehler:

```
hackmdPostgres_1 | STATEMENT:  SELECT "id", "patch", "lastContent", "content", "length", "authorship", "createdAt", "updatedAt", "noteId" FROM "Revisions" AS "Revision" WHERE "Revision"."noteId" = '0ae9767f-6362-47c9-97fe-c8fc49e9d6ca' ORDER BY "createdAt" DESC;
hackmd_1         | Unhandled rejection Error: SequelizeDatabaseError: column "authorship" does not exist
hackmd_1         |     at /hackmd/app.js:638:22
hackmd_1         |     at /hackmd/lib/models/revision.js:162:27
hackmd_1         |     at /hackmd/lib/models/revision.js:219:22
hackmd_1         |     at /hackmd/node_modules/async/dist/async.js:359:16
hackmd_1         |     at iteratorCallback (/hackmd/node_modules/async/dist/async.js:933:13)
hackmd_1         |     at /hackmd/node_modules/async/dist/async.js:843:16
hackmd_1         |     at Model.<anonymous> (/hackmd/lib/models/revision.js:291:18)
hackmd_1         |     at Model.tryCatcher (/hackmd/node_modules/bluebird/js/release/util.js:16:23)
hackmd_1         |     at Promise._settlePromiseFromHandler (/hackmd/node_modules/bluebird/js/release/promise.js:512:31)
hackmd_1         |     at Promise._settlePromise (/hackmd/node_modules/bluebird/js/release/promise.js:569:18)
hackmd_1         |     at Promise._settlePromise0 (/hackmd/node_modules/bluebird/js/release/promise.js:614:10)
hackmd_1         |     at Promise._settlePromises (/hackmd/node_modules/bluebird/js/release/promise.js:689:18)
hackmd_1         |     at Async._drainQueue (/hackmd/node_modules/bluebird/js/release/async.js:133:16)
hackmd_1         |     at Async._drainQueues (/hackmd/node_modules/bluebird/js/release/async.js:143:10)
hackmd_1         |     at Immediate.Async.drainQueues (/hackmd/node_modules/bluebird/js/release/async.js:17:14)
hackmd_1         |     at runCallback (timers.js:666:20)
```

**Comment by jackycute** [comment]
Hi @tiiger 
Please provide your version and environment information.
And if you upgrade from old version to `0.5.0`, you should run migration manually.
See more here: https://github.com/hackmdio/docker-hackmd#migration-to-050

BTW, please use English here, I might misunderstand your need via Google Translation.

**Comment by SISheogorath** [comment]
To fix the google translate issue:

> Nach dem Start mit `docker-compose up` bekomme ich beim erstellen einer neuen Notiz einen HTTP 500 und im Log steht folgender Fehler:

Is translated in English:
> I started using `docker-compose up` but when I try to create a new notice I get an HTTP error 500 and the error code below:

**Comment by tiiger** [comment]
Sorry, I didn't had the intention to write in German. Just happened there accidentally. 😆
Since I couldn't get it to work. I installed it directly (without the use of Docker) and have no problems so far.
For the sake of fixing this issue, I will try it again in a few days. 😄

**Comment by SISheogorath** [comment]
Feel free to reopen if the issue still exists.

**Comment by kittel** [comment]
When trying to use docker-compose to set up hackmd with this repository I am experiencing the same problem as the original poster.

The attached log file shows the command line script of a freshly pulled compose attempt (with no previous database volumes existent)

In summary:
After pulling the container the app unsucessfully tries to apply migrations:

    grep -e "ERROR" -e "STATEMENT" -e SequelizeDatabaseError bugreport.txt
    database_1  | ERROR:  relation "public.Users" does not exist
    database_1  | STATEMENT:  ALTER TABLE "public"."Users" ADD COLUMN "accessToken" VARCHAR(255);
    database_1  | ERROR:  relation "public.Users" does not exist
    database_1  | STATEMENT:  ALTER TABLE "public"."Users" ADD COLUMN "refreshToken" VARCHAR(255);
    app_1       | Unhandled rejection SequelizeDatabaseError: relation "public.Users" does not exist
    app_1       | Unhandled rejection SequelizeDatabaseError: relation "public.Users" does not exist
    database_1  | ERROR:  relation "public.Notes" does not exist
    database_1  | STATEMENT:  ALTER TABLE "public"."Notes" ADD COLUMN "savedAt" TIMESTAMP WITH TIME ZONE;
    app_1       | Unhandled rejection SequelizeDatabaseError: relation "public.Notes" does not exist
    database_1  | ERROR:  relation "public.Notes" does not exist
    database_1  | STATEMENT:  ALTER TABLE "public"."Notes" ADD COLUMN "authorship" TEXT;
    database_1  | ERROR:  relation "public.Revisions" does not exist
    database_1  | STATEMENT:  ALTER TABLE "public"."Revisions" ADD COLUMN "authorship" TEXT;
    app_1       | Unhandled rejection SequelizeDatabaseError: relation "public.Revisions" does not exist
    app_1       | Unhandled rejection SequelizeDatabaseError: relation "public.Notes" does not exist
    database_1  | ERROR:  relation "public.Notes" does not exist
    database_1  | STATEMENT:  ALTER TABLE "public"."Notes" ADD COLUMN "deletedAt" TIMESTAMP WITH TIME ZONE;
    app_1       | Unhandled rejection SequelizeDatabaseError: relation "public.Notes" does not exist
    database_1  | ERROR:  relation "public.Users" does not exist
    database_1  | STATEMENT:  ALTER TABLE "public"."Users" ADD COLUMN "email" TEXT;
    database_1  | ERROR:  relation "public.Users" does not exist
    database_1  | STATEMENT:  ALTER TABLE "public"."Users" ADD COLUMN "password" TEXT;
    app_1       | Unhandled rejection SequelizeDatabaseError: relation "public.Users" does not exist
    app_1       | Unhandled rejection SequelizeDatabaseError: relation "public.Users" does not exist
    database_1  | ERROR:  column "authorship" does not exist at character 59
    database_1  | STATEMENT:  SELECT "id", "patch", "lastContent", "content", "length", "authorship",     "createdAt", "updatedAt", "noteId" FROM "Revisions" AS "Revision" WHERE "Revision"."noteId" = '15eb0b93-6351-432d-819d-d1b835621c3b' ORDER BY "createdAt" DESC;
    app_1       | 2017-11-01T07:34:54.790Z - error:  SequelizeDatabaseError: column "authorship" does not exist

[bugreport.txt](https://github.com/hackmdio/docker-hackmd/files/1433449/bugreport.txt)

**Comment by SISheogorath** [comment]
Do you use `hackmdio/hackmd:0.5.1`?

**Comment by kittel** [comment]
Actually I do not know / did not specifiy this explicitly.
As of yesterday I just cloned this repository and tried to follow the steps given in the README.

As of the content of docker-compose.yml it seems the app image is in fact hackmdio/hackmd:0.5.1 (line 30). But as I said I just cloned the repository with no old docker volumes available.

**Comment by SISheogorath** [comment]
Ah, yes, the 0.5.1 release is not changed, that's why the error is still there. In the `latest` image it's solved.

Since there was no release since 0.5.1 there is currently no stable release for now. But there should be a new release soon. Details: https://github.com/hackmdio/hackmd/issues/531#issuecomment-340758447

So the issue itself is resolved but not for the current stable release.
