### ISSUE TITLE
hackmd-lite failed to build because of missing bash package

### ISSUE THREAD

**Issue by toshi0123** [hackmdio/docker-hackmd#17]
hackmd-lite is based on alpine linux. Bash is not installed.  
But hackmdio/CodeMirror's release.sh requires bash.
```
#!/bin/bash
```
My forked repository which added the bash package succeed to build.

**Comment by SISheogorath** [comment]
Good news!

The current lite image is very experimental. It'll move to the master branch with tons of improvements when PR #14 is merged. (Will happen this week(end)). 

There will be further improvements in no time, once it's merged and setup to build our images :)

So please be patient for this PR and then feel free to contribute your best ideas ❤️

**Comment by toshi0123** [comment]
Oh...You already knew the issue. I didn’t check PR#14. 
I love HackMD. This is best tool. I’m looking forward merging it!
