### ISSUE TITLE
Update to latest Hackmd version

### ISSUE THREAD

**Issue by wirehack7** [hackmdio/docker-hackmd#19]
Will this project still get updates to the latest hackmd version?
Or shall we fork an maintain it ourself?

It's a bit behind.

**Comment by SISheogorath** [comment]
docker-hackmd currently provides the latest official release of HackMD CE which is still 0.5.1.

We will change soon with a new HackMD CE release to the new build system build by #14.

**Comment by SISheogorath** [comment]
Fixed by merging #14
