### ISSUE TITLE
How to set the callback URLs for docker-hackmd?

### ISSUE THREAD

**Issue by virgil** [hackmdio/docker-hackmd#27]
I currently have docker-hackmd up and running (thanks for this BTW!), and now I'm attempting to get Github OAuth working.  Where do I enable this for docker-hackmd?

**Comment by SISheogorath** [comment]
You can use the environment variables documented in the HackMD main repository.

See: https://github.com/hackmdio/hackmd/blob/master/docs/guides/auth.md

**Comment by virgil** [comment]
I'm still attempting to make this work.

I have the install at: http://notes.ethresear.ch/

I'm attempting allow login via github.  But despite enabling this config I still don't see any login-with-github button.  Suggestions?

```
{

    "production": {
        "urladdport": true,
        "email": false,
        "db": {
            "username": "hackmd",
            "password": "hackmdpass",
            "database": "hackmd",
            "host": "hackmdPostgres",
            "port": "5432",
            "dialect": "postgres"
        },
        "github": {
           "clientID": "1b11c39XXXXXXXXXXXX",
           "clientSecret": "ce459efXXXXXXXXXXXXXXXXXXXX"
         },
        "domain": "notes.ethresear.ch",
        "allowfreeurl": true,
        "usecdn": true
    }

}
```

**Comment by SISheogorath** [comment]
You only need to add the [environment variables](https://github.com/hackmdio/hackmd#environment-variables-will-overwrite-other-server-configs) in the following section of the docker-compose.yml:

https://github.com/hackmdio/docker-hackmd/blob/8e2a743a89bb6667d10aa7033f590685752e165b/docker-compose.yml#L31-L37

Details how to use it: https://docs.docker.com/compose/compose-file/#environment

**Comment by virgil** [comment]
thank you!
