### ISSUE TITLE
How to add robots.txt

### ISSUE THREAD

**Issue by bruce0205** [hackmdio/docker-hackmd#28]
Cause I don't want any search engines to crawl my private hackmd web site, is there a way to create robots.txt?

Thanks in advance.

**Comment by SISheogorath** [comment]
Right now there is no way to create a robots.txt.

My personal suggestion would be to put it on the reverse proxy in front of HackMD, but of course that's no perfect solution. But for the scope of this repository, it's the only one.

Feel free to open an issue on https://github.com/hackmdio/hackmd
