### ISSUE TITLE
Some import/export keys cannot be set via ENV

### ISSUE THREAD

**Issue by tiirex9** [hackmdio/docker-hackmd#29]
It's annoying to have to build the Dockerfile myself just because I have some configs that cannot be configured via ENV:
google drive(google/apiKey, google/clientID), dropbox(dropbox/appKey) (for impot/export) can only be configured in config.json, not via ENV regarding the documentation on the main github repository: https://github.com/hackmdio/hackmd

**Comment by SISheogorath** [comment]
fixed by https://github.com/hackmdio/hackmd/pull/684
