### ISSUE TITLE
Wishlist: Provide external resources(Mathjax etc.) locally

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [hackmdio/docker-hackmd#38]
Currently docker-hackmd requires resources from Cloudflare CDN, which causes loading problem on poor internet access environments.  Please host these resources locally.

**Comment by SISheogorath** [comment]
You can simply use the environment variable `HMD_USECDN=false`.

**Comment by Lin-Buo-Ren** [comment]
Thanks for the info.

**Comment by Lin-Buo-Ren** [comment]
@SISheogorath I've set and exported the `HMD_USECDN` environment variable with the value `false` before `docker-compose start`, but the page still request resources from Google Fonts, Cloudflare CDN etc.

**Comment by SISheogorath** [comment]
Please double check that you wrote `false` all lowercase and run `docker-compose up -d` because start iirc doesn't recreate the container.

**Comment by Lin-Buo-Ren** [comment]
Works now, thanks!

**Comment by SISheogorath** [comment]
By the way, thanks for your work on the Wiki @Lin-Buo-Ren
