### ISSUE TITLE
Can't find postgresql Charts when trying to install on k8 via helm

### ISSUE THREAD

**Issue by arthurlogilab** [hackmdio/docker-hackmd#43]
```
$ helm install ./docker-hackmd/kubernetes/chart     --set image.tag=latest 
Error: found in requirements.yaml, but missing in charts/ directory: postgresql
```

I tried to git clone https://github.com/kubernetes/charts but that didn't solve it. 

Sorry am a k8/helm newbie, this might be really trivial.

**Comment by SISheogorath** [comment]
Probably @yuanying can help here.

There is also a better PR to move all these informations to official charts:
https://github.com/kubernetes/charts/pull/3570

Apart from that, try the following:

```
helm install stable/postgresql

helm install ./docker-hackmd/kubernetes/chart     --set image.tag=latest
```

**Comment by arthurlogilab** [comment]
@SISheogorath thanks for you answer. 

I tried your suggested commands but I get the same error.

**Comment by arthurlogilab** [comment]
It seems I was missing a `helm dependency update` somewhere. Maybe that can be added to the README.

**Comment by yuanying** [comment]
@arthurlogilab I found that this chart has some issues, please use kubernetes/charts#3570

thanks
