### ISSUE TITLE
404-Error if referrer disabled or spoofed

### ISSUE THREAD

**Issue by CryptKid** [hackmdio/docker-hackmd#48]
Every time, I try to open a new note, no matter if logged in or not, i get a 404 while creating a new note if disabled the referrer
Tested with firefox on Ubuntu 18.04 and on Arch Linux.
Hackmd:1.0.1-ce

**Comment by SISheogorath** [comment]
Yes, this is known and was changed in version 1.1.0-ce.

Since we used the `referer` before to match the websocket to the note. With 1.1.0-ce this was changed to use a usual url parameter for the websocket instead.

**Comment by ccoenen** [comment]
Here's the relevant ticket, it also links to the code change.
https://github.com/hackmdio/hackmd/issues/623
