### ISSUE TITLE
How to add toolbar to editor?

### ISSUE THREAD

**Issue by flemssound** [hackmdio/docker-hackmd#51]
How can I add the toolbar to the editor? 
<img width="834" alt="screen shot 2018-06-04 at 20 38 43" src="https://user-images.githubusercontent.com/7942983/40935111-5a136238-6837-11e8-8548-acb7cc0df06a.png">

**Comment by ccoenen** [comment]
This is a Hackmd.io only feature. There's currently some work being done offering something similar to hackmd Community Edition.
