### ISSUE TITLE
Volume for image uploads

### ISSUE THREAD

**Issue by pirate** [hackmdio/docker-hackmd#67]
How do we configure a volume to store user uploaded images?

I just migrated my docker container from an old machine to a new one and seem to have lost all our uploaded images.  They must be somewhere in the old aufs docker diffs.

Ideally going forwards we'd like to have a dedicated named docker volume for storing those files so we can back them up properly separately from the database.

**Comment by SISheogorath** [comment]
First of all please check https://github.com/hackmdio/codimd-container#migrate-from-docker-hackmd

And then, yes, by default when you use the local filesystem to store pictures, then they are gone when you don't create a new volume explicitly. But it's not like the entrypoint script wouldn't warn you about it:

https://github.com/hackmdio/docker-hackmd/blob/55c58abb016ec93d80add8c2b08c90876cac48ed/resources/docker-entrypoint.sh#L18-L33

Hope that helps. Also please keep the following PR in mind: https://github.com/hackmdio/codimd-container/pull/16
